# This workflow is for testing locally with act
# ./builder/prepare.sh
# export DOCKER_HOST='unix:///var/run/podman/podman.sock'
# sudo act -P ubuntu-latest=-self-hosted
name: Rechunk Github Tester
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The ref tag to bundle'
        required: true
      prev:
        description: 'Use previous ref'
        type: boolean
        default: true
jobs:
  online_test:
    permissions:
      packages: write

    runs-on: ubuntu-24.04
    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin
      - uses: actions/checkout@v4
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7
      - name: Download images (optional)
        run: |
          sudo podman pull ghcr.io/hhd-dev/rechunk:latest
          sudo podman pull ghcr.io/ublue-os/bazzite-deck:${{ github.event.inputs.ref }}
      - name: Run Rechunker
        id: rechunk
        uses: ./.
        with:
          ref: 'ghcr.io/ublue-os/bazzite-deck:${{ github.event.inputs.ref }}'
          prev-ref: ${{ github.event.inputs.prev == 'true' && 'ghcr.io/hhd-dev/bazzite-automated-deck:stable' || '' }}
          rechunk: 'ghcr.io/hhd-dev/rechunk:latest'
          version: '${{ github.event.inputs.ref }}'
          labels: |
            io.artifacthub.package.logo-url=https://raw.githubusercontent.com/ublue-os/bazzite/main/repo_content/logo.png
            io.artifacthub.package.readme-url=https://bazzite.gg/
            org.opencontainers.image.created=<timestamp>
            org.opencontainers.image.description=Bazzite is an OCI image that serves as an alternative operating system for the Steam Deck, and a ready-to-game SteamOS-like for desktop computers, living room home theater PCs, and numerous other handheld PCs.
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/ublue-os/bazzite
            org.opencontainers.image.title=bazzite
            org.opencontainers.image.url=https://github.com/ublue-os/bazzite
      - name: Upload Image
        id: upload
        shell: bash
        run: |
          sudo skopeo copy ${{ steps.rechunk.outputs.ref }} docker://ghcr.io/hhd-dev/bazzite-automated-deck:latest
          sudo skopeo copy ${{ steps.rechunk.outputs.ref }} docker://ghcr.io/hhd-dev/bazzite-automated-deck:stable
          sudo skopeo copy ${{ steps.rechunk.outputs.ref }} docker://ghcr.io/hhd-dev/bazzite-automated-deck:${{ steps.rechunk.outputs.version }}
        